import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoadingAnimation } from "@/components/loadinganimation/loadingscreen";
import Header from "@/components/mainpage/topheader/header";
import Footer from "@/components/mainpage/buttomfooter/footer";
import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CaviteVenture",
  description: "Generated by IT NUMOA",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>CaviteVenture</title>
        <meta name="description" content="Generated by IT NUMOA" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoadingWrapper>{children}</LoadingWrapper>
      </body>
    </html>
  );
}

function LoadingWrapper({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        dangerouslySetInnerHTML={{
          __html: `
            setTimeout(() => {
              document.getElementById('loading')?.remove();
              document.getElementById('content')?.classList.remove('hidden');
            }, 5000);
          `,
        }}
      />
      <div id="loading">
        <LoadingAnimation />
      </div>
      <div id="content" className="hidden">
      <SpeedInsights/>
        <Header/>
        {children}
        <Footer/>
      </div>
    </>
  );
}

export default RootLayout;